# https://ashwin9798.medium.com/nginx-with-docker-and-node-js-a-beginners-guide-434fe1216b6b
---
services:
  # solr-dev:
  #   image: ghcr.io/hgnc/solr-search:2024-01-31t17.31.36
  #   ports:
  #     - "8983:8983"
  pgnc-data:
    build: sql/.
    container_name: pgnc-data
    volumes:
      - pgnc-data:/var/lib/postgresql
  pgncdb:
    image: postgres:17.0
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: pgnc
      POSTGRES_DB: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgnc-data:/var/lib/postgresql
    depends_on:
      - pgnc-data
  nodeserver:
    build: api/.
    ports:
      - "5500:5000"
    depends_on:
      - pgncdb
  nginx:
    restart: always
    build: server/.
    ports:
      - "8008:80"
    depends_on:
      - nodeserver
volumes:
  pgnc-data: