# https://ashwin9798.medium.com/nginx-with-docker-and-node-js-a-beginners-guide-434fe1216b6b
---
version: '3'
services:
  solr-dev:
    image: ghcr.io/hgnc/solr-search:2024-01-31t17.31.36
    ports:
      - "8983:8983"
  pgnc-data-dev:
    build: sql/.
    container_name: pgnc-data-dev
    volumes:
      - pgnc-data-dev:/var/lib/postgresql/data
  pgncdb-dev:
    image: postgres:16.4
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: pgnc
      POSTGRES_PASSWORD: pgnc
      POSTGRES_DB: pgnc
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgnc-data-dev:/var/lib/postgresql/data
  nodeserver:
    build: api/.
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build: server/.
    ports:
      - "8008:80"
volumes:
  pgnc-data-dev: